import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter_tts/flutter_tts.dart';

import '../core/errors.dart';

/// One voice the device can speak with.
class VoiceOption {
  const VoiceOption({required this.name, required this.locale, this.label});

  final String name;
  final String locale;
  final String? label;

  String get display {
    final pretty = label ?? name;
    return locale.isEmpty ? pretty : '$pretty · $locale';
  }
}

/// The AI voice-over runtime.
///
/// Design note, because it explains every odd-looking choice below: the
/// platform has **no paid TTS service** and must not grow one — the product is
/// free to run. So a voice-over is generated by the *device* speech engine and
/// the `sounds` row keeps the script (`voice_script`, migration 00021), which
/// means the same voice-over can be re-rendered on any other device instead of
/// being locked to the handset that recorded it. If a device has no engine,
/// the feature degrades to "saved script, play it on a phone" and says so.
class VoiceOverService {
  VoiceOverService();

  FlutterTts? _tts;
  bool _unavailable = false;

  /// True when a device engine answered at least once.
  bool get isAvailable => !_unavailable;

  /// Web can speak a preview through the browser engine but cannot write a
  /// file, so a voice-over uploaded from the web build would have no bytes.
  bool get canSynthesize => !kIsWeb && !_unavailable;

  Future<FlutterTts?> _engine() async {
    if (_unavailable) return null;
    final existing = _tts;
    if (existing != null) return existing;
    try {
      final tts = FlutterTts();
      await tts.setSpeechRate(0.5);
      await tts.setPitch(1.0);
      await tts.awaitSpeakCompletion(true);
      _tts = tts;
      return tts;
    } catch (_) {
      _unavailable = true;
      return null;
    }
  }

  /// The voices the device offers, deduplicated by name+locale. Returns an
  /// empty list when the platform refuses to enumerate (web, some desktops).
  Future<List<VoiceOption>> voices() async {
    final tts = await _engine();
    if (tts == null) return const <VoiceOption>[];
    try {
      final dynamic raw = await tts.getVoices;
      if (raw is! List) return const <VoiceOption>[];
      final seen = <String>{};
      final out = <VoiceOption>[];
      for (final entry in raw) {
        String name = '';
        String locale = '';
        String? label;
        if (entry is Map) {
          name = '${entry['name'] ?? entry['identifier'] ?? ''}';
          locale = '${entry['locale'] ?? ''}';
          if (entry['displayName'] != null) label = '${entry['displayName']}';
        } else if (entry != null) {
          name = '$entry';
        }
        if (name.isEmpty) continue;
        if (!seen.add('$name|$locale')) continue;
        out.add(VoiceOption(name: name, locale: locale, label: label));
      }
      out.sort((a, b) => a.locale.compareTo(b.locale));
      return out;
    } catch (_) {
      return const <VoiceOption>[];
    }
  }

  Future<void> select(VoiceOption voice) async {
    final tts = await _engine();
    if (tts == null) return;
    try {
      if (voice.locale.isNotEmpty) await tts.setLanguage(voice.locale);
      await tts.setVoice(<String, String>{
        if (voice.name.isNotEmpty) 'name': voice.name,
        if (voice.locale.isNotEmpty) 'locale': voice.locale,
      });
    } catch (_) {
      // A device that rejects an explicit voice still speaks with its default;
      // that is a better outcome than refusing the preview.
    }
  }

  Future<void> setRate(double rate) async {
    final tts = await _engine();
    if (tts == null) return;
    try {
      await tts.setSpeechRate(rate.clamp(0.1, 1.0));
    } catch (_) {}
  }

  Future<void> setPitch(double pitch) async {
    final tts = await _engine();
    if (tts == null) return;
    try {
      await tts.setPitch(pitch.clamp(0.5, 1.5));
    } catch (_) {}
  }

  /// Speaks [text] out loud. Interrupts whatever was speaking.
  Future<void> speak(String text) async {
    final tts = await _engine();
    if (tts == null) {
      throw const AppException('tts', 'This device has no speech engine, so the voice-over cannot be previewed.');
    }
    try {
      await tts.stop();
      await tts.speak(text);
    } catch (error) {
      throw AppException('tts', 'The voice-over preview failed on this device.', cause: error);
    }
  }

  Future<void> stop() async {
    final tts = _tts;
    if (tts == null) return;
    try {
      await tts.stop();
    } catch (_) {}
  }

  /// Renders [text] into an audio file and returns its absolute path.
  ///
  /// Android writes into the app cache and returns the path; iOS writes into the
  /// documents directory and returns the path too. A platform that cannot write
  /// files returns null, which the composer turns into "preview only".
  Future<String?> synthesizeToFile(String text, {required String name}) async {
    final tts = await _engine();
    if (tts == null || !canSynthesize) return null;
    try {
      final dynamic result = await tts.synthesizeToFile(text, name);
      if (result is String && result.isNotEmpty) return result;
      if (result is Map && result['path'] is String) return '${result['path']}';
      return null;
    } catch (_) {
      return null;
    }
  }

  void dispose() {
    final tts = _tts;
    _tts = null;
    if (tts == null) return;
    try {
      unawaited(tts.stop());
    } catch (_) {}
  }
}
